name: autoCheck-in
run-name: autoCheck-in 🚀
on:
  push:
    branches:
      - main
  schedule:
    - cron: '1 16 * * *' #国际标准时间：北京时间00：01
    - cron: '30 15 * * *' #北京时间23：30
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tencentVideoSign-in-Actions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code one
        run: |
          git clone https://github.com/arlettebrook/tencentVideoSign-in-Actions.git
          

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11' # 使用适当的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tencentVideoSign-in-Actions/requirements.txt  # 安装依赖

      - name: Run check-in-status
        run: |
          python tencentVideoSign-in-Actions/main.py --login_cookie "$LOGIN_COOKIE" --login_url "$LOGIN_URL" --login_url_payload "$LOGIN_URL_PAYLOADLOAD" --PUSHPLUS_TOKEN "$PUSHPLUS_TOKEN" --GET_VIP_INFO_URL_PAYLOAD "$GET_VIP_INFO_URL_PAYLOAD" --IQY_COOKIE "$IQY_COOKIE" --LOG_LEVEL "$LOG_LEVEL" --BDUSS "$BDUSS" >> run.log
        env:
          LOGIN_COOKIE: ${{ secrets.LOGIN_COOKIE }}
          LOGIN_URL: ${{secrets.LOGIN_URL}}
          LOGIN_URL_PAYLOADLOAD: ${{secrets.LOGIN_URL_PAYLOADLOAD}}
          PUSHPLUS_TOKEN: ${{secrets.PUSHPLUS_TOKEN}}
          GET_VIP_INFO_URL_PAYLOAD: ${{secrets.GET_VIP_INFO_URL_PAYLOAD}}
          IQY_COOKIE: ${{secrets.IQY_COOKIE}}
          LOG_LEVEL: ${{secrets.LOG_LEVEL}}
          BDUSS: ${{secrets.BDUSS}}

      - name: Checkout code two
        uses: actions/checkout@v2  
        
      - name: Append Success Log #追加成功日志
        run: |
          echo "$(date +%Y-%m-%d\ %H:%M:%S) - 今日任务执行成功" >> run.log
      - name: Upload log #上传日志
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: run.log
      - name: Push log #更新日志
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: auto-checkin
          branch: main
